apiVersion: batch/v1
kind: Job
metadata:
  name: pdf-processing-job
spec:
  parallelism: 4
  completions: 4
  completionMode: Indexed
  template:
    spec:
      containers:
      - name: pdf-processor
        image: us-central1-docker.pkg.dev/gdrive-410709/vllm-serving-repo/pdf-processor:latest
        env:
        - name: BASE_URL
          value: "https://the-eye.eu/public/Books/Bibliotheca%20Alexandrina/"
        - name: BUCKET_NAME
          value: "gdrive-410709-vllm-13b-demo-bucket"
        - name: HUGGING_FACE_REPO
          value: "Disperser5601/Sentinel-Intelligence-Codex"
        - name: HUGGING_FACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token
              key: token
        - name: NUM_PODS
          value: "4"
        #When Kubernetes creates pods for an Indexed Job, it automatically sets the
        #JOB_COMPLETION_INDEX environment variable in each container. 
        #By removing the default value in the Python code, we ensure that:
        #If the job is correctly configured as an Indexed Job, each pod will get its
        #unique index. #If there's a configuration issue, the job will fail fast with
        #a clear error. #We don't need to manually expose the variable through fieldRef
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: gcr-json-key
  backoffLimit: 100
