apiVersion: batch/v1
kind: Job
metadata:
  name: pdf-processing-job
spec:
  parallelism: 4
  completions: 4
  completionMode: Indexed
  template:
    spec:
      containers:
      - name: pdf-processor
        image: us-central1-docker.pkg.dev/gdrive-410709/vllm-serving-repo/pdf-processor:latest
        env:
        - name: BASE_URL
          value: "https://the-eye.eu/public/Books/Bibliotheca%20Alexandrina/"
        - name: BUCKET_NAME
          value: "gdrive-410709-vllm-13b-demo-bucket"
        - name: HUGGING_FACE_REPO
          value: "Disperser5601/Sentinel-Intelligence-Codex"
        - name: HUGGING_FACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token
              key: token
        - name: NUM_PODS
          value: "4"
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: OnFailure
  backoffLimit: 4
