apiVersion: batch/v1
kind: Job
metadata:
  name: text-classification-job
spec:
  parallelism: 4
  completions: 4
  completionMode: Indexed
  template:
    spec:
      containers:
      - name: text-classifier
        image: us-central1-docker.pkg.dev/gdrive-410709/vllm-serving-repo/text-classifier:latest
        env:
        - name: HUGGING_FACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token
              key: token
        - name: BUCKET_NAME
          value: "gdrive-410709-vllm-13b-demo-bucket"
        - name: DATASET_NAME
          value: "ccdv/patent-classification"
        - name: NUM_PODS
          value: "4"
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: OnFailure
  backoffLimit: 5