\begin{tabular}{|p{142.3pt}|p{142.3pt}|p{142.3pt}|} \hline State of Alabama & \multicolumn{1}{p{142.3pt}|}{**Case Number**} \\ Unified Judicial System & \multicolumn{1}{p{142.3pt}|}{**WRIT OF EXECUTION**} & \multicolumn{1}{p{142.