## Appendix A Appendix

By Jim Sullivan

Color By Tom Tullis &

Don Greer

Illustrated by Joe Sewell

[MISSING_PAGE_FAIL:3]

[MISSING_PAGE_EMPTY:5]

[MISSING_PAGE_FAIL:6]

[MISSING_PAGE_EMPTY:8]

[MISSING_PAGE_FAIL:9]

drop tanks; or margin. The remaining external identification feature was the deletion of the upper boxes from the sliding convey for better visibility. In some cases, only production FBU-L/TOF-10: Crossing crime from the factory with the earlier traced-style canopy, but those were soon replaced as the clear city became available.

The FBU-10: Locarii exclusively used the Odosys Sea Blue point scheme applied at the factory. The national insights was originally applied in the Blue surround and later was replaced by the borelines. While water and bar height. In January 1974 Ioff stripes were added to the White ban on the wing and factory. Their insights are related for the remainder of all US. Scuser providers, The FBU-10:L/O-10: NOR was run the focus in US to be operational assigned to U.S. carries. With the Bud bounce and put wing deep technology overcoron, the US. Navy began carrying fast carriers with Corank. In December of 1944, the Marines were then fed to go ahead, carrying off-12-and VBF-12-ahead USS USSESES. These ten sensors were scanned by other USMC spacators aboard other carriers. The FBU-10:L/O-10: OS OS regularly replaced the sweep distance from FBU fields at the standard carrier-based fighter coupling body Navy and Marine students.

The remaining FBU-10: Leslie of the Coast with the FBU-10: which was a field modification that added a K2-1 full camera mounted in the lower rear section of the foreign railway between the wing trailing edge and the forward on the other wall together. This camera was controlled from the occipital and provided both pre-situ and post-strike photographic satellites. This modified FBU-10: FS was used by the NSW and Marines.

The FBU-10 and FIO-10: Class was used by the USMC, Royal Navy and Royal New Zealand Air Force showing the Second World. The Taier, years in the FBU-10: Control for service with El Salvator and Industries. During a new between these two South American countries in the early 1960s, both opposing sites and Coast is flight against Corank and Montage. The US-10:L/O-10: OS Coast finished their current on the Beverlines from the national to eventually were phased out during the early 1950s by the more advanced and improved FBU-10: The FBU-11: safety of Corank were the largest number produced of any Crosist variate.

## References

* [1] A. A. K., "The FBU-10: A Some early production FAU-1s were returned from the South Pacific, northwest and assigned to training units in the states. This FAU-1, full number 465, was assigned to VF-OTA- (Operational Training Unit For FAU) and was engaged in practice carrier readings on the field at NAS Access/Exotics, Florida, CT February 1945. (National Archives) FAU-2 (Boston of VOF-1: utilized an engine failure shortly after last resort from NAS Alliance (City, first orders and crash handed at Organization Beach 0 to 4 January 1944. The pilot made a great down funding near the surf limit and the Corsari suffered strike category damage and never free again. (USN Via Dave Lucchady)The F44J-11 error denotes drawing model controls, metric, popular controls, fast mixture. The open area at left is the radio compartment. (Voxquib)

(Right) The F44J-1 main instrument panel, open and side console. The F4J had no occupied bottom and was open beneath the hot troughs. The stick and strobened nodes peak are also visible. The customized number and go to the instrument panel was installed to minimize injury in the event of a crash. (Voxquib)

The Paul A Whitney R-200-MW engine was capable of producing over 2,000 kg giving the F4J-1 to up speed in excess of 415 mph. This powerful 18-cylinder, has been row Nugy engine was "white-of-the-art" for the Second World War. (United Technologies)

[MISSING_PAGE_FAIL:16]

_Bayes Baby_ was an F441-A (1985) of VIV-277 on Guam during September of 1944 turned and shown by a pilot from Louisiana. The standpoint highlights us carried on each side of the ongoing cognitive. During the Second World War the World War the World Twe sequence was created with minutes after this. This Coast survived the war and was a strictment from inventory on 21 January 1946. (B. R. Turnage)

A pilot of these F41-A consists of VIV-277 Wild Tarens on a combat mission out of West Field on Guam during September of 1944. The F41-A at the bottom was Rubo 44900 which carried the baseline numbers in Yellow. White twin was applied to the propeller box, tail come and ports of the vertical and horizontal simulator. (B. R. Turnage)

This F41-A (Bulio 17856) of VIV-17 was from by Lieutenant Junior Grade Tom Killive who made a focal stick landing on _M1888_ Island after suffering engine failure during March 1944. Killive was credited with a total of four and a half falls during his warline service. (National Archives)

This F6-A was assigned to AB6-2 (Air Base Group Twe) at HAS San Diego, California and participated in Project 20d, an attempt to test a functionalized speed record on 22 May 1945. Bad weather toward the end of the flight prevented a successful record flight. The fin and rauder carried Blue and White checks. (Goodyear)
Figure 1: (Right) Operating from Rothhammer, this F401-41A Circular (Bulio 4958) also another "poor" or "virt-224" papers to head out on a lighter browser mission armed with a 1,000 sound behind under the testing on 2 September 1984. The target for this Marine Corasar was a Japanese installation on Taroo Island, Maloosa, (W.E. Schroborough)

Apr-1-15, also acquired 164, of VPR-48-reprepations to launch from the night deck of UBS WaxSP during October of 1948. This Corari carried the Gloasy Sea Blue paint scheme with White heatings. The small White number 168 on the nose was assembled on a Black rectangle. (National Aerches)

(Left) Priging over low-dim, this FO-10 (Bello 8821) of the 2nd MAW propters to land during only of 1948. The Goodyear outbreak outbreak outbreak on a chronic set of leak and was never from the combat. It sat out the way is located at the end of the field. (Bill Dett)

Full-10 of V-5 line the flight deck of UBS FRANKLIN prior to a strike. This was one of the last missions from "Big Ben" shape Japanese bombs dropped at her on the morning of 91 March 1948 UTED the FRANKLIN in a heating function. Although damaged beyond repair, the did not stick and eventually sealed to New York Harbor. (National Aerches)

Fully loaded with avenia tanks and eight for each IFAR pockets, an FAU-10, able turn her 31, of VPR-228 tons up for an quick on Japanese forces on the mountain peak of Kami Tata, in Corari Outmaro on 15 June 1948. (USILC)

[MISSING_PAGE_FAIL:22]

[MISSING_PAGE_FAIL:23]

A pair of Primium FG-10-16 KG-340 (photo 87146) and KG-340 (photo 872425) by over the Ohio counterspider during flight testing on 3. July 1945. These factory fresh Ceraseras did not see combat due to their flat arrival at the close of the user. At first February was applied to the top of the Gloss Blue Teleustice to act as an anti-gate panel. (Goodway via nick Ravison)

(Higgin) This FG-10-10 (photo 872425) was one of a small number of Ceras that were made available to El Salvador. Later in their service lives the aircraft were given a cammodage point scheme, although the Yellow band around the Institute opportioned the cammodage. In Fig. 10-10 there was just to the US. Adding September of 1975 and was redirected as REZZ. Rehurek and repaired, the Coralar law appears on the market sideward circuit. Both Stucker)

The FAIR circuit. Overall arrives was modified by Vaught to a two set configuration during 1945. Anything too late to be of any practical value to the war effort, the modification never went into production or service use. (Vought vs All Scheme)

This FG-10 (photo 835728244) carried the aircraft side number 46 and belonged to the 14 Square Royal Now Zealand Air Force. The nut was based at Honda Airport, Tokyo, Japan on 8 December 1946 as part of the occupation process. (Dave Luchabrupt)

[MISSING_PAGE_FAIL:26]

[MISSING_PAGE_FAIL:27]

[MISSING_PAGE_EMPTY:28]

This F44-Q4 (Bulio 80779) was equipped with a BAT mission on an addressing launch artifact (October 1916). The missile launch is three successful; however, the rule-site never became operational with F44 quadrants. (U.S. Navy via Full Address)

Pazed on display at Philadelphia during 1945, the F44-Q4 (Bulio 8170) was assigned to W12-22 and carried the name _GNAF4_. EGFER on the astronomical side of the engine

coving, along with the squadron mission. (a.o. J. Kohn)

The production line at Voigtator factory of Stuttcher, cf was packed with Cerriss during August 1988. Photoactive was used except providing F44-6 for the U.S. Navy and Magnus Corps. This variant of the Corsi captured service in April of 1988 with greatly improved performance over earlier variants. (Youq99)

The F44-Q4 (Bulio 4078) was one of the F44-4 prototypes modified from a F44-LA atrname. This Corsi was equipped with a popular primer, although this made no appreciable gain in performance and was not incorporated into production variants. (Voigt)

[MISSING_PAGE_EMPTY:37]

[MISSING_PAGE_EMPTY:40]

[MISSING_PAGE_FAIL:41]

F4U-5

Vouth first new fiber F4U-5 Coaster on a April 1996. It was mounted by a 24.49 kg box per R-200-3200E engine and had a web speed of 47.0 m/b. The ceiling speed of the F4U-5 was 227 mph with a range of over 1,100 square mills. With two days it could carry a total of 549 gallo of total. A number in the F4U-5 was a part of 2084 N-5 camera located in each sub, additionally, we sample of carrying the Sight I New F4U-5. We use the windows equal every probe, though units of seconds. A total of 223.74 U-5 was produced by Vought along with 214.49 U-53, U16, F4U-5, and 304 U-54. The total production of the F4U-5 series comes to 5688 seconds.

In Improvements to the F4U-5 series included automatic cost flips, interwoiler flaps and oil cooler doors, a modernized comfortable circuit board, higher canopy and a redesigned engine coupling that featured low rain on exposing the lower price of the coupling. The F4U-5 was the first Coast to utilize ten percent covered out time upside and control windows.

The F4U-5 was the right right figure with a subcuting timeout procedure similar to the wheel on the earlier F4U-2 and F4U-4N. The F4U-5 was the "winerized" variant of the F4U-5N and featured dider blocks on the wing leading edges and the vertical and horizontal tail.

The F4U-5P was the photo reconnaissance variant which was distinguishable by the side frisheng sliding door blister and the end their air-shaped blister located railway on the vertical 

[MISSING_PAGE_EMPTY:45]

[MISSING_PAGE_EMPTY:46]

A F44-S4, state number 113, of V7-81 cells down the flight deck of USS NOVAVAY for a deck run takeoff. The propeller hub and tip of the fin was trimmed in White. The Pratt & Whitney h29-020-207 gauge produced 2,300 to and the F44-S could reach a top speed of 47 mph. (5.8.Nw)

(Sign) Taking a wave-off from the LSD aboard USS FRANGLE D. ROOSEVELT, This F44-S (photo 121729) side another 401, of V7-81 nodes around another another approach during October of 1953. To counter the torque of the WB ongoing, the pilot has locked in full right rauder to avoid a potentially fatal torque roll. (Rich Corbata)

F44-S4, state number 11, of V7-82 nodes at M48 Chemy Point, North Carolina, was hointed about a carrier at the Norfolk located Base on 2 April 1949. This Corbata was Glossey Sen Blue with brute markings. (Robert Rafterne)

[MISSING_PAGE_EMPTY:48]

Figure 1: The **F4U-9** (blue 12268) of WIA-1 carried the units **MV** on the test. The aircraft was normally based at Marine Corps Air Station E Toro, California during 1949. (City Janssen)

The AU-1 [F4U-6] was the final variant of the Cesair to be produced for use by the U.S. military. It was from primently by the Marine Corps and was used extensively in Korea. The Naval Reserve also utilized them for a period of time after 1954 and referred their latest one during early 1956.

The AU-11 filter was 0.31 January 1952 and was equipped with a 2,300 bp PW R-2800-SWW single-speed superbined engine. This Cesair was a dedicated ground attack aircraft and carried ten motorious programs for rock rock rock rock rock and bow time upon typical for radio-s. If all test tasks, hows or emplan. The AU-11 was generally similar to the F4U-5 slot did not have the initial savings of the engine cost wing. Internal assurance was sectioned to the F4U-5 (four 200km camera). Vograph produced a total of 117 of these seventh ground attack coatings. After service with the U.S. military, a number of them were made available to the French Navy. It should receive they participated in three conflicts and served faithfully sent retired in 1956.

[MISSING_PAGE_FAIL:55]

[MISSING_PAGE_EMPTY:58]