[MISSING_PAGE_EMPTY:2]

The Legend of the

There will never be another aircraft like the B-17. Times have changed, war has changed, people have changed.

When the Army set out its 1934 requirements for a bomber able to fly at 250 miles per hour, with a service ceiling of 25,000 feet and six to ten hours endurance, Boeing was ready to give it a try. Their highly successful Model 247 airliner had led to many advances and bridged many technical gaps.. The company was already working on the giant XR-15, the largest aircraft to fly when it finally took off in 1937, So, while most manufacturers submitted twin-engine designs, the team under Edward C. Wells in Seattle started working on Model 299.

Construction began on August 16, 1934 and, borrowing liberally from the XB-15 and Model 247, Boeing produced a super aircraft, free of the gawkness which characterized so many bombers of the thirties. The first Fortes carried eight crew members, was powered by four 750 horsepower engines, and weighed 43,000 pounds. It was sixty-eight feet nine inches long, with a wingspan of nearly 104 feet, and there were four gun blisters, with provision for a fifth.30 caliber gun in the nose.

The acid test took place on July 28, 1935, when test pilot Les Tower took Model 299 up for the first time. When the injury minute test flight was over a lot of apprehension was gone and a lot of work justified. On August 20 the plane was taken to Wright Field for evaluation by the Air Corps. The Fortes easily matched up to the claims made for her.

Suddenly, on October 30, the big silver plane stalled skeleningly into the ground on takeoff. As it burned fierely the five crewmen were dragged out. Tower and the co-pilot, Major Player P. Hill, died. The investigation proved that the controls had been locked, unknown to the pilots, and when the aircraft lifted it became uncontrollable. Even so, the Air Corps' projected order of sixty-five Forteses was dropped and only thirteen examples were asked for, perhaps a temptation to fate in itself.

With these thirteen **YB-17**s the foundation to the legend was laid. One was assigned to Wright Field for destruction testing, the other twelve went to the G. H.O. Air Force for America's first heavy bomber group, the 2nd. In December 1936 Captain Stanley Untasted brought the first YB-17 into Seattle after a brief flight, and as onsoakers opened the steel and bronze brakes, quick to overheat, fused from overcuts. The Forteses' nose dug a two hundred and forty foot, $5,000 furrow. The B-17 could not have made a worse entry into the field of inter-service squabbling, misery allocations, distrust of "strategic bombing" and general anti-military feeling that was prevalent in the United States.

Drastic action was needed, and taken. The biggest publicity campaign in Air Corps history began. Records of every kind were relegated to pale history by the new bomber. The YB-17 set aside for destruction-by-testing passed one big test quickly and unconventionally. Running into a storm, it was flipped over on its back and began plummeting downward. By the time it was pulled out of that dive any tests were superfluous. So that Forteses was modified into the next model, the **YB-17A**, equipped with turbo superchargers which added 55 mph to its maximum speed.

In February 1938 six Fortresses flew from Miami to Buenos Alres to attend the presidential inauguration ceremonies there. During the five thousand mile goodwill flight they stopped once, at Lima. That was really long range in 1938, and the flight won the Mackay Trophy for outstanding aerial achievement. In May, Fortresses flew nearly eight hundred miles out to sea to intercept the Italian liner Reax, to the dismay of many Navy men. This unsolicited demonstration resulted in their being restricted to flights no further than one hundred miles out from the coast. Past that was apparently Navy water. In all, the first Fortresses notched up over one million miles in the air without a single serious accident.

The first production model of the bomber was the **B-17B**, and like all but the first, Model 299, it was powered by Wright Cyclone engines. The pneumatic brakes were dropped in favor of hydraulics, but little else was needed to be changed. When the Lend-Lease agreement was made, the Royal Air Force asked for the Fortress, and got twenty of the next model, the **B-17C**. The American bomber would first see action with the British.

The results, due mainly to tactical mis-use by the RAF, were not far short of tragic. The first aircraft sheared off its undercarriage on landing in England, another fell to pieces as it landed after being shot-up over France, a force of three was wiped out on one mission, another accidentally burned, yet another was lost during testing, and one dyed straight into the ground. The guns froze, armor was inadequate....and the RAF passed the survivors on to Coastal Command.

The Air Corps brought their later C models up to **B-17D** standard with more armor and self-sealing tanks, and most went to the 19th Bomb Group's deference in the Philippines. Half were destroyed during the initial Japanese attacks and the rest fought as best they could until only one was left - the famous **Swoose**, B-17D 40-3097.

The **B-17E**s, born of experience, were almost new aircraft. The rear section of the aircraft was entirely changed, with a huge, graceful tail and twin-gun tail turret. Fifty caliber Browning machine guns replaced the lighter. 30 caliber guns in all but the nose positions, and the other modifications all added up to a machine which could carry out the daylight bombing role. First on the list of supply was the 7th Bomb Group in Java, the initial batch reaching them in January 1942. Their presence was immediately felt. The old and worn 19th Bomb Group got B-17E, as did the 5th, 11th and 43rd Groups. But the B-17's days in the Pacific were numbered when Colonel Frank Armstrong swung himself aboard the 97th Group's **Butcher Shop** on August 17, 1942. Twelve B-17E's took off from Polebrook, England and bombed France, the first light jab of what was to become the Fortresses' fight.

In May 1942 the last B-17E was produced, and two days later, on May 30, the first **B-17F** rolled out. Externarily little different from the B-17E, it incorporated over four hundred changes. The main visual difference was in the nose, where the greenhouse effect of the B-17E was replaced by a one-piece Piexiglas nose, incorporating the optically flat bomb alting panel.

Internally, there were very important changes. The B-17F had self-sealing oil tanks, extra wing fuel cells, (called Tokyo Tanks), improved brakes, better oxygen system, and so on.

B-17F's were produced by three companies - Boeing in Seattle, Douglas at Long Beach, and Lockheed-Vega at Burbank. Forward firepower was a major problem for 8th Air Force Forforeses, and many variations on this theme appeared. One B-17F, **Bomb Boogle** of the 91st Group, had a unique extended cheek window which added to forward firepower, but not to the necessary extent. Twin nose guns, with a special frame for support, were tried, but the recoil was tremendous and the mounting was unwieldy. The ball-and-socket mounts provided in the Plexiglas nose piece were inadequate for direct forward fire, and the ultimate answer, or best answer, was a single gun recessed in a triangular cut-out at the tip of the glass nose.

Because it was the problem area, the nose of the B-17F was where most modification took place. One B-17F, 41-2548, serving with a 5th Air Force Troyo Carrier Group as an armed transport, had a B-17E nose piece fitted. Cheek positions, purely a flush enlargement of one of the factory-fitted side windows on early B-17S, were improved by mounting a specially fabricated, bulged gun position.

Experiments were tried with twin waist guns, and even a 20mm cannon in the tail when German fighter attacks from the rear caused concern, but basically the B-17 remained a bomber equipped with thirteen.50 caliber machine guns in the three turets and six or swen hand-held positions. The VB-40 project, involving heavily armed B-17F's for une purely ascepts, was a failure, but solved the forward firepower problem.

The YB-40's were fitted with a Bendix "chin" turret, and this was the salient feature of the final B-17 model, the B-17G. The chin turret was not the only difference, but it was by far the most important.

The first B-17G was delivered to the USAAF in September 1943, and the chin turret was warmly received. Only the sight and remote lifting control were inside the nose; the twin guns, recoil dampers, and gun chargers were all housed in the turret beneath the nose. The guns had an excellent field of fire and the nose was left virtually unobstructed.

There were more than a score of "different" B-17G's, but it was not until the B-17G-90-BO, B-17G-55-VE, and B-17G-50-DL that the next recognizable change took place. This was the installation of the Cheyenne tail turret, which was a ball-like turret with a better field of fire and a reflector gunlight in place of the old rding and bead. This stubby, round turret decreased the Fortress' length by five inches.

The B-17G was also the first model to have enclosed waist positions, in place of the earlier hatch which had to be slit back before the guns could be swung out. These waist windows varied - there were both flush fittings and "bulged" fittings. The waist positions were also staggered to allow the gunners more movement.

The radio operator's single hand-held gun had been of dubious value and toward the end of 1944 it was abandoned on the B-17G. Like the waist positions, this gun emplacement had been enclosed to decrease discomfort on most B-17G's.

Being over a ton heavier than the B-17F, the B-17G suffered in comparative performance. While the B-17F was capable of nearly 300 mph at 25,000 feet, the B-17G was rated at 287 mph. With bombs and fuel and the necessities of formation flying the standard required was for B-17G's to be able to operate at 25,000 feet for about six hours at around 160 mph average speed.

Many B-17G's recorded notable mission tallies, but four aircraft in the 91st Bomb Group chalked up the incredible total of 537 missions between them. There was Hi Ho Silver, named begause she was one of the first unpainted arrivals at Bassingbourn, standing out like a sore thumb in the olive Grab formations. She made 130 missions and survived the war.

**Wee Willie** joined the 91st in the summer of 1943, and had flown 127 before April 8, 1945, when a fak hit ruptured a fuel tank, enveloping the aircraft in blazing gasoline. The shattered left wing folded back, broke free, and twelve seconds later **Wee Willie** was only fiery, scattered chunks of metal trailing wispy streamers of smoke. Somehow the tall gunner and co-pilot escaped, the sole survivors of a made-up crew of officers and enlisted men who needed just a couple more missions to complete their tours.

**Outhouse Mouse**, from the 323rd Squadron, carried four crews through their tours, bombed Berlin a dozen times, and flew a total of 139 missions.

**Nine-Q-Nine** flew her 140th mission on April 25, 1945, to just nose out her sister ship as the 91st's leading aircraft. This old B-17G was received at Bassingbourn on February 25, 1944, and flew her first mission five days later. By January 15, 1945 she had completed one hundred missions. She made Berlin eighteen times and in all her missions she never turned back once due to mechanical failure. In all she had twenty-one engine changes, four wing panel changes, fifteen main tank changes and eighteen Tokyo Tank changes. Her fuselage, wings and tail were highlighted by patches where she had been holed. To one crewman who flew in her she was "a big, dumb, tired aircraft which performed normally".

But for every **Nine-Q-Nine** there were scores of Fortresses which never carried one crew through a tour. The Fortress was a lucky airplane, good to her crews, but some were luckier than others. The unwary were claimed quickly.

In all there were 12,731 Flying Confresses - the Model 299, thirteen VB-17G, one VB-17A, 3B-17B's, 3B-17C, 42 B-17D's, 512 B-17E's, 3405 B-17F's, and 8680 B-17G's. Now there are only a handful left.

**Spool**, also from the 11th Bomb Group, These B-17E's carried no group markings and were in the Boeing factory finish.

This old B-17E had many stories to tell. She is **Yankee Doodle**, the aircraft which carried General tra Eaker on the first mission to Rouen. She was later attached to the 91st Bomb Group as a utility aircraft, and carried yellow 322nd Squadron codes. Group artist Tony Stareer added the painting of Unite Sant to the original neat, yellow name. This B-17E was fitted with a 20mm xenon in the tail, but the experiment was abandoned when the recoil started popping tweets. The arrangement of B-17E, B-17E **Chemantits Pappy**, B-17G **Just Nothing** and unpainted B-17G **General** fle was occasioned by the visit of General Dwight Eisenowr to the 91st base at Bassingbour.

Cherley Horse, 42-29571, was a B-17F-55-B0 from the 358th Squadron, 303rd Bomb Group. She carries grey squadron codes (VR-L), but the aircraft letter on the tail is yellow. The circular C in the triangle appeared on a number of 303rd aircraft, but most carried the block C appearing on other aircraft in this September 1943 formation. (LIFE Magazine)

U.S. BRONNING. 50 cal.

HEAVY MACHINE GUN

Stomy Weather of the 323rd Bomb Squadron after the March 4, 1943 Hamm mission. She was a B-17F-40-B0.

Bomb Boogle, 42-5763, the second-last B-17F-15-VE, was described by war correspondent John Steinbeck as a hard-luck ship. She has an unusually wide field-fitted cheek gun position. The nickname was painted in white and yellow.

\\ \end{tabular} 
\begin{tabular}{c c}  & Miami Clipper, from the 91st Bomb Group. The Norden bomb sight is in place in her nose. She was a B-17F-20-B0, 42-29815. \\ \end{tabular}

This 571st Squadron, 300th Group B-17F was salvaged by the Germans as part of their project to rebuild B-17S. When the American army was closing in, this hang near Chateaufort was destroyed by the enemy, then abandoned. It appears work had begun on this aircraft, with the addition of a nose from another Fortress.

A B-17F-90-B0, 42-30157, Hell's Belles overshot the funway at Bassingbourn in July 1943, completely wrenching the #2 engine from its mounting.

The 305th Group's **Pathy Ann**, a B-17F-115-B0, on the September 6, 1943 Nutrient mission. She carries the white squadron codes of the 366th. White replaced the earlier gray letters on many aircraft in this unit.

Like many 8th Air Force B-17's, 42-5729 shows evidence of earlier markings. She is the fifth B-17F-10-YE, and it was from this block of twenty aircraft that the thirteen gunship YB-40's came. However, the first seven were not converted, contrary to some reports. This photograph clearly shows the mounting for the single gun fired by the radio operator.

Nicknames on 8th Air Force Fortisess were a harmless form of rludify which never ceased to reuse the time of the merformined. The crew of this B-17F-70-BO from the 381st's 534th Squadron called 42-29751 Mia-Aborino, but someone evidently objected. So they changed it to the apparently acceptable **Stuff**, which must have amused those with a knowledge of English expressions. In common with the rest of her group, this aircraft carried squadron codes on the fuselage, and aircraft letter on the tail.

**Egg Haid**, a grimy B-17G-15-VE from the 535th Bomb Squadron, 381st Group, based at Ridgewell in Essex. The aircraft on the left is a red-tailed Fortress from the 398th Group, with her codes N7-G closely grouped atf of the national insignia. The "bulging" of the enclosed waist windows can be clearly seen in this photograph.

Pilot1 Packin' Mama was a B-17G-10-DL, the first of the Douglas B-17G's to be produced in quantity. Early B-17G's went into combat without the usual check gun positions. There is provision for the older ball-and-socket mounting in the center window.

(Far Right) A B-17F-75-DL, one of the severity-six Douglas B-17F's fitted with chin targets, from the 413th Squadron of the 96th Bomb Group. The squadron codes are in gray, but the aircraft letter is in white on the tail and fuselage. The B-51's are from the 3rd Scout Force.

[MISSING_PAGE_FAIL:31]

**Times A-Wasini**, L-L-Q, **A2:102504** of the gist's ddiat lombo Squadron. Bert Stiles records in **Serenade to the Big Bird** that the name "didn" strike any deep chord" in him, but the ground crew made the choice, as was often the case. Stiles flew with Sam Newton's crew, and the plane later changed hands and took Ed Garner's crew on their last twenty-five missions.

Little Miss Miss Mischief was back from Cologne, on October 15, 1944. She had been one of many B-17's carrying out the second of three daily attacks on this prime industrial target. Her fuselage was blasted open, her ball turret so mangled that it was inconceivable that the gunner could have survived.

Paul McDowell, from Nebraska, was the second owner of Little Miss Mischief. As far as he was concerned she was too damned slow. She had suffered wing spar damage on an earlier mission, but a couple of new engines had brought her closer to standard. So on October 15 McDowell was staring through his thick windscreen, flying one more long mission. Then a rudder pedal went limp.

The microphone was out too, but up on the flight deck McDowell and his co-pilot, Herman Balaban, didn't know what was happening. Sergeant James Hobbs, the engineer, dropped down from his bicycle seat beneath the upper turret and squeezed back through the bomb bay,past the radio room, and into the art section of the ship. A minute later he returned, his eyes bulging. McDowell caught something about "big hole back there". When he went back to look and found it was big enough to push a calf through he recalls being "impressed". The bombarder went back to check it out, ran out of oxygen, came back already effected by an overdose of nitrogen-heavy air, and insisted they must all bail out immediately. Sapped back on oxygen the quickly reconsidered.

The right waist gunner, Glenn Slaughter, had felt the metal beneath his feet erupt, throwing him from his gun. He they, looking down to the ground through scores of large, small and medium sized holes all around him. Unable to believe he was still whole, he dazedly watched blood seeping from his heavy boot. Most of the heel of his left foot was gone, but he was soon taken care of.

All thought of the bomb run and Cologue out of his mind, McDowell fought with his nose-heavy airplane.

In the mangled ball turret, gunner Ed Abdo was trapped. Someone showed a blanket down through the gaging hole to protect him from the lcy slipstream.

McDowell was at 27,000 feet and he needed to get down fast. He sent the co-pilot back to get hold of some of the severed control cables, but he grasped the wrong one and Little Miss Miss Missified tried harder to dive. McDowell brought Balaban back to fight the control column, and made his way through to the waist, stationing the radio operator at the bomb bay. The radio man would have to relay signals to and from pilot and co-pilot as things got better or worse. McDowell grabbed the right cable first time and they re-trimmed the aircraft for hands-off flight at around 110 miles an hour.

The heavy pressure on the control wheel eased, and the situation was in hand, but McDowell still had problems. That big hole back there was naturally number one, and Ed Abdo trapped in the ball meant he had to make a landing, and a perfect one. He was more nervous than scared. Back in the waist, looking at the sky all around him, he had felt sure that if the Fortress cracked in two he would be able to get out, because he was already wearing a back-pack chute.  but if she broke up on landing. Fire was always his biggest fear, and that was remote now, but he was surely nervous.

By the time they arrived at Bassingbourn the engineer was working hard, operating the trim tab and rudder cables from the waist, and the ball turret gunner, having administered morphine to himself, was frost-bitten but still alive. His role as one of the luckiest men in the hit Air Force cost him one little toe.

McDowell got her down, and Little Miss Miss Missified went to the hangar. For a while her future looked doubtful, but Colonel Frank Kamykowski of the 444th Subep Report ditf like wasting airplanes. He had a spare rear end from an old olive draw Fortress and decided to make a special effort. Before the repair operation was over, Little Miss Missified contained bits and pleess from thirteen different aircraft. While her front end was still mostly B-17G 42-97880, built by Vega, her new rear end was made by Boeing in Seattle. Little Miss Missified flew fourteen or fifteen more missions, for a grand total of fifty, before she crashed at Bassingbourn. She was quite a lady and is the subject of our cover painting by Don Groer.

Probably the only Fortress named after a racehorse, **Man O War** It had an enviable record with the 322nd Squadron before fighters got her early in the air battle over Mersepep on November 2, 1944. She was serialized 42-38038, the last 1-76-25-D, and carried the code letters LG-V. She had flown 15 missions in March 1944, when this photograph was taken.

It was an unlucky pair of B-1-7's which rolled out together at Seattle one day in 1943. The first, 42-30e03, became Las Vegas Aveager with the 306th Bomb Group and ended her days on June 21, 1944 near Amsterdam. The second, 42-30e004, went to the 100th Group and was reported missing in action on October 4, 1943, during a particularly bloody week in the 8th Air Force. When allied troops captured an airport between Versailles and Chateaufort in September 1944 they found her and whole hangers of partially salvaged allied aircraft, demolished by the retreating germans. The retreation of the original 100th Bomb Group markings indicates that the aircraft was destined for clandestine work with the Luftwaffe,* [15] A. B.-17G-35-DL in the pattern over Polebrook, England, home of the 351st Bomb Group. 42-107124 is from the 510th Squadron.

Flanked by younger, silvery sisters, old

**Nine-O-Nine** prepares to unload her bombs.

OR-C is **Priority** Gal, OR-S is **Sweet** **17**.

A B-17G-50-DL from the 303rd Bomb Group,

crashed at Molesworth. The aircraft letter on

the tail is yellow outlined in black, the serial is

yellow and the surround to the triangle is red.

[MISSING_PAGE_EMPTY:51]

[MISSING_PAGE_EMPTY:52]