[MISSING_PAGE_EMPTY:2]

[MISSING_PAGE_FAIL:3]

[MISSING_PAGE_FAIL:5]

(D-ISTQ), based on the licensed de la Cierva C19 and C30 unogros. It was rejected out of hand by the RLM as being too temperamental, as rotocraft were considered to be far too early in their development to be of any practical use.

The Bayerstein Fluggengenweke (Messchemnitz) submitted the BF 163 (D-IUCT), but BFW was heavily engaged in development of the BF 109 fighter aircraft, and the BF 163 prototype was completed to make it be considered.

On the basis of tests at technicin several improvements were made to the Storch. The slats were shortened, the continuous acle was deleted, and the wing was straightened to eliminate dihedral.

By the time its rivals were flying, the Storch was in serial production and coming off the assembly line. In early spring of 1937 the first 10 pre-production FI 156A-to-8B legal network, the factory and were immediately put into military service trials. The official public debut of the Storch was made with one of these pre-production machines on 1 August 1937, when D-I/MR was demonstrated at the Fourth International Flying Meet at Zurich-Debendorf air-field in Switzerland where it gave a spectacular STOL performance. The performance of the Demieor D17 and the BF 109 at this meet also swept the board; Germany again was a world in paper with these prototypes.

The initial FI 156A-1 production aircraft (serials 615 to 620) were produced as utility aircraft suitable for both civilian and military use. Fiesef barred planned to produce a commercial growth should trouble leading edges under the designation FI 156B-1, but with war lowening just over the horizon, there was little possibility of producing a commercial aircraft, and even though a market existed, the B-series did not materialize.

By the summer of 1937 the Laffwaffe had fully evaluated the Fw 156A-0 and had come to fully appreciate the military potential after the aircraft could up in battle situations. It could fly as two as 33 miles power in still air, and with a residual it could virtually hover over the ground. Both the Laffwaffe had the Weltmann could envision an almost endless number of tanks for the Storch, from artillery spoting to supply dropping and even including bombing.

The Storch was large for its job; the U.S. Army Fiber1-4 Grassberger carried out nearly all the same tasks with a 65-Heapover engine rather than the 240 hoverover of the Argus.

One set of tests against figures proved the superb defense of the nimble nitric aircraft, when figures arrived with pan cameras could not manpower to get a single picture on their gun camera film when the Storch was flying at around 3 miles per hour.

Production of the FI 156 was 227 in 1939 and 216 in 1940 and almost doubled to 430 in 1941. A total of 2.871 FI 156 Streetrand were delivered to the laffwaffe with small numbers being passed on to Germany's allies -- Bulgaria, Croatia, Finland, Hungary, Italy, Romania, and Slovakia -- all of which were fighting on the Eastern Front.

Surprisingly, there was no reported use of the Storch flying night harassment missions over the front lines on the Eastern Front.

[MISSING_PAGE_FAIL:7]

### Fi 156C-1 Storch

The B-series was to be a Storch built for the commercial market, but it was quickly abandoned.

On the basis of combat experience in Spain, defensive armament of an aff-firing 7.9mm MG15 machine gun was installed and tested on the pre-production F156C-0. It was mounted in an inf and fired through a circular fan lens at the rear of the cockpit. The machine gun was not added to the production F156C-1 which was primarily a staff transport and lalsion aircraft.

Small numbers of Slocube were exported to Finland (two) and Switzerland (six), and Herman Gorling presented a Storch to Mussouli and even one to Stalin.

Salin was so impressed with the Storch that he ordered it to be copied. One of the important features of the Storch was the air cooled engine that started even in the cold of Russian winters. A factory was set up in Elotain to manufacture a copy of the Storch, but the German army overn to before production could begin.

[MISSING_PAGE_EMPTY:14]

## Appendix A Appendix

### The F156C-2 Storch feature

The F156C-2 Storch feature as standard an aff-firing Rheumatall-Borisy 7.9 mm MG15 testing pain in a flexible mount in the rear of the cockpit, as tested on the pre-production F156C-0. A permanent seat for an emergency third crew member was also installed in the C-2, and provision was made for mounting a vertical camera in the rear of the cockpit, reducing crew capacity to two persons. Late machines were modified to carry wounded on a litter.

Right) The F156C-2 differed little from the F156C-1 except for the addition of a defensive hit firing flexible 7.9 mm MG 15 machine gun mounted in a circular lens. The gun was more for respect than real protection; the slow speed of the Storch was its best defense from attacks from the air.

Below) 2E-RA carries an infantry badge on the cowling; the aircraft code is black outlined in white, and the tausage band is yellow. This reconnaissance machine is being prepared for an early morning mission over Russian lines.

**(Above) A Rumannal general arrives in a Storch for a conference with the German high command on coming operations. The Rumannal Army was one of the more effective of Germany's allies, although it was poorly equipped. The Rumannals would eventually receive some 45 discrete.**

**(Right) 9.0(#).6.2 was the reconnaissance staffelt of Lehrbeschwader 2 (Training Wing 2) and was equipped with three He 126s, one ff 109, and two F 158C-2s. All aircraft carried a giffin in a enabled embn on the nose.**

**(Below) An S5 general is posted on a late afternoon tour of his troops. The SS always had priority of equipment including the Storch.**

[MISSING_PAGE_EMPTY:22]

(**Above) A simple set of skills attached to the long stroke undercarmage solved the snow problem and extended the winter usefulness of the Storch. Even in very deep snow the Storch could take off and and if the snow was frozen hard enough.**

Main skis

(**Right) A heavy but very effective whitewash camouflage has been smeared on all upper surfaces of D4-HP, but not obscuring the code letters or national insiglias. The lower surfaces are Light Blue with no whitewash.**
(Above) A hard, frozen snow surface such as this was ideal for a ski-equipped Storch to land on and take off. However, under such conditions both hardings and takeoffs required more likely operating from a cleared and maintained landing field.

[MISSING_PAGE_FAIL:31]

[MISSING_PAGE_EMPTY:34]

[MISSING_PAGE_EMPTY:35]

## Appendix F F 156U

In 1940 the Eirobungssteille at the Rechlin test center evaluated the Storch as a possible anti-submarine aircraft. Three ETC 50 bomb reads were installed on an uprated F156C-2, one on each set of wing starts at their wing attachment points, and a third on the centerline between the cross broring of the landing gear. Each bomb pack could carry a single 110-pound SC 50.

An ASK-R bomb release was mounted over the port window, and a ZSK 244 fuse box was mounted over the door on the stuxford side. A Rev C/12/D dive bombing sight was mount-on the instrument panel coming.

Trials were also conducted with a 298-pound captured French depth charge but, like the bombing trials, did not result in an anti-submarine Storch.

(Below) Three ground crewmen, called schwarze men (black men) because of their black uniforms, load an SC 50 bomb onto the stuxford ETC 50 bomb neck of the F1 56U. The bomb rakes were attached to the wing bracing at at the the front and rear wing attachment points.

[MISSING_PAGE_FAIL:37]

[MISSING_PAGE_FAIL:40]

F156D-1 Storch

Manufactured alongside the C series, the Fi 156D-1 was primarily an ambulance Storch used by Witsenstuenstuft (rescue squadrus). An enlarged upward-hinged loading door was installed on the steward side of the fuselage just behind extended at-fuselage plexiglass panels which were hinged to swing downward.

When both the fuselage panel and the glass cabin panel were open, a patient on a lifter could be accommodated along with an attendant on the emergency seat. If no attendant was accompanying the wounded, the emergency seat could be removed and a second lifter could be carried.

The D-1/Trop was equipped with sand filters, emergency landing packs, and an enlarged oil filter.

(Below) The Fi 156D-1 ambulance was easily recognized by the addition of a triangular window at the rear of the cabin. The machine gun was removed, and hardware was installed to accommodate up to two litters. A red cross was usually painted on the fuselage, top and bottom of both wings, and sometimes the wall.

The F156 Storch had a role to play wherever the German army was in World War II. Coded KR-H2G, this Storch is seen on a frozen lake in Norway.

[MISSING_PAGE_EMPTY:49]