## Appendix A Appendix

**COPRIGHT 5 1991 SQLDRON/SIGNAL Publications, INC.**

1115 CROWLEY DRIVE CARROLLTON, TEXAS 7501-5010

All rights reserved. No part of this publication may be reproduced, stored in a retrieval system or transmitted in any form by any means electrical, mechanical or otherwise, without written permission of the publisher.

**ISBN 0897-275-256**

If you have any photographs of the aircraft, armor, soldiers or ships of any nation, particularly warting, snapshots, any other alarm with us and maple Squadron "Signat" looks all the more interesting and complete in the future, Any photography record to suit the code and the original returned. The floor will be fully credited for any photos used. Please send them to:

**S Squadron/Non-Satellite Publications, Inc.**

1115 CROWLEY DRIVE.

**Carrollo, TX 75011-5010.**

**Photo Credits:**

Bundesarchiv

George Punka

S.M. Coates

Hans Redemann

Hermann P. Dorner

Gene Stafford

E.C.P.A.

Hans-Heit Stapfer

Manford Griehl

Squadro/Signal

Imperial War Museum

Wolfgang Tamme

R.M. Meixner

M. Tertimen

Jim Mosko

Zdenek Titz

National Archives

U.S. Air Force

Hans Obert

**Author's Note:**

Research into the Ju 88 fighter variants has uncovered a great many "gray areas" and conflicting data concerning the aircraft's development. As a result, this book covers the major Ju 88 fighter variants and provides additional information on some of the more questionable areas. This information was added to provide the reader with a comprehensive overview of the Ju 88 complicated (and sometimes handling evolution.

**2**

[MISSING_PAGE_EMPTY:4]

## Introduction

When Adolf Hitter's Reischstuftrahrministerium (State Aviation Ministry - RLM) issued a specification for a Schnellbomber (fast bomber) to Germany's aviation industry during 1935, it simultaneously created Germany's most important wartime bomber, as well as one of its most popular heavy fighters.

The Juss Juss, Rashed by the Junkers Flugge und Moterenwerke A.G. of Desau, Germany, not only surpassed the RLMs expectations as a multi-purpose medium bomber, butindefinitely excluded as _Ring Zenitore_ (day destroyer) and Schwerer Nachtiger (heavy night-fighter), a role which the Third Reich would later desperately need. By the end of the war, approximately 39.40% Juss Rashed had been manufactured out to atoll 15.000 machines.

When the prototype Ja88V-1 first flew on 21 December 1936, there was no thought of using the aircraft as a fighter. It soon became obvious, however, that the Ju88 possessed excellent handling qualities, high speed and long range - all of which could be advantageous in the _Zentferro_. Despite this, primary prototype development remained solidly focused on the evolution of the first production bomber variant, the Ju88 A-1.

When the Ju88A-1 entered production during the Spring of 1939, the favored _Tag Zenitore_ in use with the Luftwait was the smaller, twin-tailed, twin-engined Messershrift of 11.0 Despite the fact that the Bt 11.0 held a great deal of promise and was personally favored by Reichsmanskopf Hermann Goring, it lacked range and was later found to be outcased by British single engined fighters. As an alternative, Junkers designers proposed that the long range Ju88 be armed with a fixed battery of forward firing guns in the nose as a supplement to the Bt 11.0s. The RLM, adhering to the bomber only concept of the Ju88, subsequently granted permission for construction of Ju88 genotypes (originally referred to as the Ju88A) go a strict low-priority busist.

The first airframe believed to be reserved for conversion was the Ju88V-7 bomber prototype (GT+) AE. The Ju88 fighter modification consisted of three fixed 7.92M MG 17Machine guns and one MG-FF 20MM cann, all mounted to protrude through the strawod nose glass. The underlying ETC bomb reads were eliminated and the forward ventral gonad was raised over with a tapered finish. This arrangement reduced the maximum weight of the bomber airframe and increased the aircraft's top speed to 295 mph, some 15 mph faster than the Ju88A-1.

Two further prototype fighter conversions flew during early 1940, the Ju88Z-15 (ex-Ju88V-15) and the Ju88Z-19 (ex-Ju88V-19). Both aircraft featured sheet metal mosaes with gun ports for the forward firing weapons and a hollow "shroud" over the forward ventral gonad. This faring contained the spent casing ejector chutes for the nose guns. Another feature that was later standardized was the addition of three gun gas exhaust ports on the starobar side of the fuselage. These ports were used to vent the gun gasless from the three MG 17s. Later, the Ju88Z-19 prototype was modified with two different style bulbous extensions of the ventral gonadola. These housed a forward-firing MG 151 15MM or 20MM cannon, on an experimental basis. The Ju88Z-15 and Ju88Z-19 are believed to be the true "pattern" aircraft of the production Ju88 fighters.

[MISSING_PAGE_FAIL:6]

[MISSING_PAGE_FAIL:8]

Ju 88C-4

The Ju SSC-4 was essentially the fighter variant of the Ju 88A's bomber, which entered production during January 1994-Ju 88C-4s were dedicated fighter conversions of Ju 88A's antennas, with an bomber equipment being deleted and the lower forward fuselage windows being completely faired.

The Ju 88C-4 used the 88A's extended wingitis and inset airleons, increasing the winglength from 664 by 3 inches to 6867 by 17 inches. The FWG 10 and Fugi 6 to 16 antenna area were slightly modified and the under breakage FWG 12 rock antenna was moved further to the rear and enclosed in a plexiglass cover to reduce drag.

Power plant options allowed for the installation of either the Jum 21G or the uprated 1,400 hp June 211FE engine. With the Jum 211FE engines installed, the Ju 88C-4 reportedly had a maximum speed of 307 mph.

The nose mounted arrangement remained the same as that on the earlier Ju 88C-2, although the optional MG-FF 2000 cannot was supplied by a MG-FFM with a higher rate of fire. The option of using an alternate MG 151 cannon was also retained. The windleid mounted MG 15 machine gun, sometimes used on the Ju 88C-2, was deleted on the Ju 88C-4.

The Ju 88C-4 had an optional installation of two MG-FFM 2004 cannons in the ventral goods. When these were installed, the spent shell casings abroad on the forward goods was reduced in size and the rear fringe MG 15 machine gun was normally deleted, as the presches of the MG-FFM's cannons started on the lower gun position.

Most Ju 88C-4s retained the single upper rear fringe MG 15 machine gun used on the Ju 88C-4 were held modified with a budget rear energy with two rear gains, high height ramped areas was installed panels, and exterior appliance armor to one of the forward fisselago nose (the later by 88C-4).

The Ju 88C-4 was repeated in the production line during nearly 1942 by the Ju 88C-6. Again, only some sixty-six flights had been produced in 1941 (compared to 2,000 Ju 88 members and reconnaissance versions).

Alternate German sources have also described the Ju 88C-4 as a _Zenstor and Ferrenradure_ (developer and long-range reconnaissance) variant, with Jum 211FE engines as standard. These sources that the aircraft carried a single R50-30 camera, R20 30 camera, or an adjustable camera in the fuselago underbeit behind the rear bomb bay. These alternate descriptions have generated enough confusion that in some reference sources, two photographs of the same aircraft are identified as both a Ju 88C-2 and a Ju 88C-4.

Ju 88C-2 (Provisional)

## References

* [1] J. A. Aguilar, M.

To increase crew protection, some 4-88C-4s were retrofitted with a budget rear canopy with two MG 15 gun mounts, an armored windshield and appliance armored on the upper fuselage nose. This aircraft was cooled at 84-87 and was assigned to 10-83.2 in Roland. It was finished in a two tone Gray overpressure camorative with Light Blue undersurfaces.

Extra instrumentation was progressively added to the instrument panel of Ju 88 fighters. The structured side of the panel was enlarged and the compass was relocated in the plot’s side below the panel. The breaches of the nose guns are visible below the panel and the ammunition boxes for the MG 17 machine guns are located between the rudder pedals. Ju 88C-2/C-4

Figure 11: The 10-83.2m and 11-83.2m and 11-83.2m and 11-83.2m and 11-83.2m and 11-83.2m and 11-83.2m respectively.

[MISSING_PAGE_FAIL:13]

## Ju 88c-6

During early 1942, the Ju88C-6 was introduced on the assembly line. This fighter variant incorporated the various improvements made on its bomber counterpart, the Ju 888A-4. Although the pace of Ju88 fighter production continued to be restricted, the RLM was beginning to realize the need for Ju88C on the expanding war forms. As a result,Ju 88 fighter production for 1942 was increased to some 257 machines and the Ju88C-6 became the first Ju88 fighter variant. No reduced to an substantial numbers.

The major change between the Ju88C-4 and the Ju88C-6 was the installation of 1,400 by Ju88C-2211F or 2-Iquoid coalignes in place of the Jomo 211F or G engines. The installation of these engines featured aspulges under the covings and additional radiator air intakes in the radiator faces to feed the induction air coolers mounted below each engine. The thin chord VDM metal pipelines were replaced by broad chord VSI-1 wooden "Dedide" blades with uncharged spinners. To handle the increased weight of the improved airframe, the undercarding was strengthened and slightly larger trees instead. Curiously, a number of early Ju88C-6 retained bomber by undercarding dive brakes, however, these were quickly discarded.

The forward-firing nose and ventral radio annular treatment the same as the Ju 88C-4, including the option either a 208M MG-FF or MG 151annon in the lower nose. For greater rate defense, the single rear facing winder MG 15 points was replaced by a balged canopy with two belt-17.94700 MG 81 machine pairs in armored turrets (these fans are a faster rate of fine than the MG 15). The ventral rear firing MG 15 position was replaced by an substituted Riba 39.90700 MG 8124k (further capable of mounting either on M 15 MG 15,3181,3181,3181,3181 or 2/_Zenith_ (twin) MG 812 machine pairs. The undercaking near firing flows, however, were then detection in favor of forward-firing 20MM MG-FFM gordonza cannons.

Like the Ju88C-224C-4, the Ju88C-6 could carry 1,1000 bomb bomb had in either bomb body, or auxiliary leaf tracks (316 gallos forward, 175 gallos at). According to official loading charts, a maximum weight of 2,668 to 2860 was used with was possible by using hot internal and undercaking ETC tracks. The underlying bomb tracks were seldom used to H 88C8 and the average maximum weight was listed as 25.243 pounds. Maximum speed of the Ju88C-6 at an average weight was approximately 310 mph.

Cockpitter incoracomous were similar to previous Ju88C, although equipment updates led to the enlargement of the instrument panel to house additional instruments. The pilot's seat was changed to a fully armored seat and, for added crew protection, the internally mounted cockpit armor plating was increased. Additionally, agriculture anymore could be added to the upper fuselage also. Although early Ju 88C-6 retained bomber yue windshidlis, high-profile armor glass surfaces were progressively introduced on the production line and became the standard for the series.

Early production Ju88C-6 featured the straight rouder found on early Ju88 (both bomber and flightar variants). This was soon replaced by a balanced rouder which changed the shape of the rouder hinge in AE 2.6 direction indifferent nas was added on the mid-upper fuselage and was sealed under a circular jeteglass cover. The antenna lead wires were also changed and later by 88C-65 carried Feb 101 radio altimeter antennas under the port court wire. The under fuselage FuBl 2 rack antenna was moved slightly forward, retaining its pleississ cover.

One of the first units to received the Ju88C-6 was IN/UG 2 in the Mediterranean and North Africa, along with II and III _Onnpos_, which were based in Europe. While this seemed to indicate a primarily nocturnal role for the Ju88C, many early Ju88C-6s were,

[MISSING_PAGE_FAIL:15]

## References

* [1]

Figure 11: Starfield/Z6 26 are briefed for another mission in the Mediterranean theater. The 88C-6 camera with the _first_ Warsaw unit shight and White driving agale insights. This aircraft appears to be an anti-split-figure, equipped with an armored unshielding and mounting stubs on the nose for radar antennas. The spinner lips are in Red.(Blundsearch)

Specifications

Junkers Ju 88C-6

Wongspan & 58cd 15 inches

Length & 7cd 65 inches

Height & 15cd 1 inches

Empty Weight & 1307 pounds

Loaded Weight & 25643 pounds

Powerplant & 1700 14000 characters, jump

2711-1 (or 2-2) field coded

edges.

Armament & 7.20axn nose mounted forward

ring machine gurus, one nose mounted

20axn cartoon and two goods mounted

20axn cameras. Detensive weights

include power and lower run firing

machine runs (\(\lceil\)3.2 or \(\lceil\)3.4\(\rceil\), up to

1,100 pounds of bonds.

Performance

Maximum Speed & 310 mph

Service ceiling & 290,040 feet

Range & 1,850,020 meters

Crew & 7.10me of Four

[MISSING_PAGE_EMPTY:20]

## Night Operations 1942-44

At the beginning of the Second World War, Nazi Germany had poorly prepared for the nocturnal raids of the RAF Bomber Command, with defending Lutzwitter pilots forced to engage RAF bombers visually. Later, _Kombinerinering Nachtiged_ (Combined Night Fighting) tactics were employed over selected German cities. These tactics called for ground control radar stations to guide the fighters to the bombers within a designated fighter zone. Then the bombers were then tracked to a "flak zone" located nearer the target. The hazard of Lutzwitter flights being fired upon by their own guns as they accidentally entered "flak zones" severedly limited the effectiveness of these tactics.

A more efficient system, known as _Himberberber_ (Canopy Bed) was devised by GEN Kammhuber to coordinate ground and aerial defenses behind a chain of _Frorox_ long-range and _Wurzburg_ short-range ground radar stations. These were installed along the frontiers of Nazi acquired Europe facing England. Still, it was realized that night gifiers needed an onboard radar to individually home in British bombers once they were guided to the target by the _Himberber_ ground-controllers. Early attempts at providing the night fighters with a night eight using infrared devices met with only limited success.

The advent of Frox 202 _Licknessin BC_ onboard radar during 1942 (followed by the Frox 202 _Licknessin C-I during early 1943) the Lutzwitter night fighters were finally able to track and intercept RAF bombers with great accuracy. Unfortunately, during the late Spring of 1943, the RAF developed the capability to map the Frox 202 and 212 radars, as well as the _Wurzburg_ ground sets. This jamming was accomplished by dropping businesses of _Windows_ (a code name for foil strips out to one-half the wavelength of Fuo 202/21). This created a clouded radar image leaving German ground controllers confused as to the true size and location of an enemy formation. Fortunately, this crisis was soon resolved by the introduction of the Fuo 220 SN-2 radar.

As the radar-equipped night fighters were restored to their full capabilities, a superior Kitch, known as _Zahane Sun_ (Zane Board) was perfected for use by Ju 88 and Bf 10 units. Once a Lutzwitter flight had infiltrated a British bomber formation, it would mount a long distance pursuit in an effort to pinpoint and destroy as many bombers as possible. So successful was this tactic, that the RAF began to suffer considerable losses, the worst being the night of 30/31 March 1944, when the RAF lost intensely-seven out of 725 bombers that were dispatched against Nuremburg, Germany.

On the Eastern Front, the nocturnal air-war was less demanding since the Sovets had failed to organize a major night bombing campaign against Germany. Because of this, the two principal eastern _Nachtiged_ units, NJG 100 and NJG 200, operated on a mobile 'freerance' basis for front line tactical interceptions, using a variety of radar equipped aircraft. Like the Eastern Front, night activity in the Mediterranean and North Africa was also limited, although NJG 2 did receive a number of radar-equipped Ju 88C-6s before that unit was finally pulled back to Italy.

[MISSING_PAGE_FAIL:22]

### FuG 220 Lichtenstein SN-2 Radar

Although RAF jamming had led to disuse of the FuG 202 and FuG 212 radars, the problem was soon solved by the availability of the FuG 220 SN-2 radar, which had been developed in a close parallel to the earlier radars. The SN-2 radar was identifiable by its four largely unequal main mass, each supporting two vertical dipoles. The entire arrangement was again angled downward about five degrees.

One drawback with early SN-2s (Model O and Model A) was its lack of close contact range, its minimum range being 547 yards (over 1,600 feet). To balance this, either FuG 202 or 212 sets were briefly carried to maintain a close interception capability. With later SN-2s (Model B) the inclusion of a close-range switchover capability reduced the minimum range and the FuG 202/212 elements could be completely eliminated. FuG 220 SN-2 initially operated at a frequency of 91 MHz, offering a maximum range of approximately 3.125 miles (16,500 feet).

### FuG 220 SN-2 Radar

The flat dipoles on this JuB8C-6 have been credited as being either an aerodynamic refinement of the FuG 220 SN-2 or the aerials of the SN-3 derivative. This aircraft had the goods removed and its forward guns reduced to a single nose common. Such modifications were unofficially made to night figures as much as with JuB8 day fighters. (Manfred Grieh)

[MISSING_PAGE_FAIL:24]

_Schrage Musik_ Armament

One of the most effective armment modifications made to Indw traffic night fighters was _Schrage Musik_ (_Blaze_ or \(O\) oblique Musik), an installation of one of two upward firing cannons mounted in the fuselage spine. First appearing during late 1943, the _Schrage Musik_ installation (one or two MG-FF or MG 1512 Quad cannons) was mounted at an angle of between 70 to 80 degrees forward. This allowed the German night-fighters to attack British bombers in their blind spot (below and to the rear).

The 180 sec-6 was the first flats 88 fighter to be modified with this installation and the cannons were usually mounted in the bombay area. The empty shell scalings were often ejected through port in the lower bomb bay doors. There were several variations found on Ju 88C-6s, some of which were field modifications. To give the centerline mounted guns are deaf toffe, the overhead Fwd Fwd 10 antennas were was realigned with the addition of a horizontal mounting bracket on the vertical flip. Animing of the cannons was accomplished by using a gunset mounted on the upper canopy framing above the plot. In time, belt-fed long-parkerd MG 151 cannons became the most utilized _Schrage Musik_ weapon, with ammunition loads of up to 500 rounds per gun.

**Thes buffered late Ju 88C-6, coded 48+AS, was piloted by Hauptmann Tobber of 8,/nJQ 2, IR was equipped with Fwd 220 head, as an improved windshield, applying armor and a single gear flying 1sth 401 s running gun. Forward-guided 2008 Mo 151 Schulge Musik canons were installed in the upper fuselage. (Manford Github)**

## Ju 88c-7

Various sources have described the Ju 88C-7 as a project which was undertaken to improve the Ju 88C-7 speed and interception capability. Other sources have maintained that the C-7 was intended to be nadirless, streamlined _Bz factory_ variation of the Ju 88C-6. In either case, the Ju 88C-7 was an aerodynamic refinement of the Ju 88C-6 air-frame, described in German documents as being "like the Ju 88C-5." While some sources have indicated that there was an under luselage forward weapons on the Ju 88C-7, other German sources have described a more rearward mounted pool with two MG-FF cannons or MG 17 machine guns, again similar to the Ju 88C-5.

Production of the Ju 88C-7 was apparently limited to only a few machines. One example of a Ju 88C-7's mentioned in a wartime evaluation report dated 23 June 1942. The C-7, coded K9+VH, was reportedly equipped with two BMW 80D radial engines with a GM-1 nitrous-oxide boost system (no armament was described). Other sources have maintained, however, that June 211 in-line engines were also employed during Ju 88C-7 development.

[MISSING_PAGE_FAIL:26]

## 7 **Ju 886 Development**

As the Ju 88R began entering service, Junkers designers were already working on its replacement: a clean, more heavily armed Ju 88. The 1u 88V-S8 prototype was constructed as a composite airframe, powered by two 1.700 by BW 801D radiant engines. The wings and fuselage were similar to the Ju 88R-2, but the tail feature and the board stored vertical stabilizer and extended horizontal latitudes of the Ju 188. These modifications were carried out to improve directional stability. Revistions to the engine and wing deci-ing system resulted in the addition of shrouded hot-air outlets under the wing leading edges just outboard of the engine nucleus. For added crew, cockpitogram was increased, including the more extensive use of exterior oblique armor.

The ventral gonadal and three zones mounted MG 17 machine guns were deleted. Armanent consisted of six belt-fed 202MM MG 15 cannons, with 200 rounds per gun. Two Cannons were located in the strawden nose, ejecting their shell causing through ports under the nose. The other four corners were mounted in an understage rod mounted to offset to port. Amuntion bins for these guns were located in the forward bomb way, with the remaining bomb bomb being used for that tanks. For defense, a single, upper, rear fling MG 131 machine guns, with 500 rounds of ammonium was fitted.

The energy antenna mass was replaced by a retractible antenna mass installed on the fuselage behind the canopy. When retracted, it reduced drag and gave a clear field of fire for the rear machine gun. The understage Ful Ful 2 antenna was replaced by an Fou 25 ship antenna and run to fGGJZOO when maintaining the wire antenna mass was moved further to the rear and Fu 610 radio diameter antennas were standardized under the outer ports. At the time the Ju 88V-S8 was built, Fu 621 2rad was the frontline standard, so this was mounted on the nose with the upper mass ended sharply upward to clear the nose mounted MG 15 cannons.

Although the Ju 88V-S8 was built during the Spring of 1943, delays held up the flight tests and production until later year. The test results confirmed an improvement in handling and maneuverability, and the Ju 88V-S8 was accepted as the master pattern for the Ju 88G series (alternately being referred to as the Ju 88G V-1 or the Ju 88G-0) with the RLM ordering 700 88G series aircraft, before test flights had been completed.

[MISSING_PAGE_FAIL:28]

On some Ja 88G1s, air runs were added to the port mid-fuselage side, which became increasingly common on later Ja 88Gs. Although not usually linked, _Software Mass_ cannons were sometimes field installed on a number of Ja 88G-1s, usually positioned further forward on the fuselage, just behind the canopy. Finally, Ja 88G-1s could be out-fitted with one ETC 5000 horn rack under each inboard using panel, mainly for carrying drop tanks. During the last months of the war, however, some Ja 88Gs carried bomb loads for ground attack sorties.

The first Ju 88G-1s entered service during late 1943, with some reports recording Ju 88Gs in combat as early as December of that year. In 88G-1, Ju 88G-1 did become available in substantial numbers, however, until early 1944, and by that time the RLM had increased its production order to vote from 1.000 machines.

On 13 July 1944, Ju 88G-1 of 7/NJ (2.00464+ UR) became the most well known Ju 88G in history when it landed at the emergency RAF air base Aqubridge, Essex, after its ever accidentally few a reverse compass made after being on part over the North Sea. With this event -- the second such incident in just over a year -- the Luftwaff-fe's latest night-fighter was captured by the Alites, examined and countermeasures were quickly developed against the FuG 22 and FuG 227 equipment.

Ju 88G-1s continued to serve with the _Nxdagag_ until the end of the war, sharing duties with the next major variant, the Ju 88G-6. The Ju 88G-2, G-3, G-4 and G-5 were designations given to developmental projects which did not go into production.

## 2 Ju 88G-1 _Flensburg_

When 4R + UR was captured it carried the FuG 227 _Flensburg_ system, reportedly, only a small number being in service at this time, and not all being carried by Ju 88. With the discovery of the _Flensburg_ homber by the Alites, _Monica_ tail-warming radars were removed from RAF bombers, rendering the FuG 227 useless. As a result, it was not installed on other models of the Ju 88G series.

[MISSING_PAGE_FAIL:30]

4R+UR was a Ju 88G-1 of 7./NJG 2 which accidentally fell into British hands during July of 1944. Its secret"SN-2" and _Flemsburg_ radars were subsequently studied and neutralized by the Allies. The aircraft was painted Light Blue with a motte of Gray-Violet on the toposides.

This Ju 188F was assigned to 1.(F)/120 during 1944. The Black Green, Dark Green and Light Blue (65) camouflage was the standard factory color scheme for Ju 188s. The code letters on this aircraft have been changed with the earlier codes being overpainted in Gray.

[MISSING_PAGE_EMPTY:34]

## 11 Ju 88g-6

To increase engine power on the Ju 88Gs, Junkers re-engined the aircraft with two 1,750 hp Junkers Jump 213Ainline liquid cooled engines under the designation Ju 88G-6. This variant entered production during mid-1944. The Ju-88G-6 differed from earlier Junon power J 888 in that the cowings featured a starboard supercharger air intake, a revised radiator face, additional cooling flaps and a new system of access panels for service the engines. The Jume 213 drove 811-1 middle blade propellers, and optional flame dampening tubes could be attached over the revised exhaust stacks. With these power plants, the Ju 88G-6 could achieve a speed of 360 mph (25 mph faster than a Ju 88G-1) and attain a service ceiling of 31,515 feet. The aircraft had a combat weight of 273 pounds, approximately 660 pounds heavier than the Ju 88G-1.

Like the Ju 88G-1, the Ju 88G-6 could be equipped with one CTC 500 bomb rack beneath each inboard swing panel for drop drops by. The two port side mid-fuselage air vents (sometimes installed on the Ju 88G-1) were standardized on the Ju 88G-6, and the wing room deadstage edge at intakes were deleted. An additional equipment that has added under the rearstage, with the Feb 16J2 floor legal being positioned slightly more forward. When antennas for the optional FuG 217 tail-wairing radar were usually mounted under the port outer wing (standard Wing on the Ju 88 G-1).

Frequently, Ju 88G-6 carried upper fuselage MG 1520 _Naktive Mask_ cannons in several different arrangements. Late pottonton 1,88G-6, had these weapons installed the factory just forward of the E2 antenna over. Often fastward. Ammunition for the underside four cannon weapons pod was increased to 500 rounds per gun, and the rarefing MG 131 machine engine position was retained.

At the time that the Ju 88G-6 entered combat, the FuG 220 SN-2 was the current airborne radar, but due to Allied countermeasures, Ju 88G-6 were progressively re-equipped with later variants of FuG 220, as well as FuG 218 _Nogue_, FuG 350 Navas and finally the FuG 240 _Bart_ (during the finish weeks of the war). Many Ju 88Gs captured by the Allies at the end of the war were equipped with a mixture of radar types.

Bylat 1944, the Ju 88G-6 was sharing combat duties alongside Ju 88G-1s and surviving Ju 88C-6 and Ju 88G-2s. The Ju 88G-6's contribution to night defense, however, had little impact on the declining war situation. The fact that Germany was totally on the defensive was evidenced by the complete turnover of bomber production facilities to defensive day and night fighter production. During 1944, only 716 Ju 88 bomber and reconnaissance variants were manufactured, as opposed to 2518 filters, mostly by Refs. During the last two years of the war, the Ju 88 fighter had evolved from its early "low priority" status to equiping N3G 1, 2, 3, 4, 5, 6, 7, 100, 101, 102, 200 and other various specialized _Nachjugadgnoppen_.

W7 + AC was assigned to the II Groupe staff flight of N.30 100. The aircraft has a dual side-by-side _Schrage Music_ camera installation just behind the cockpit canopy -- one of several variations of this anti-bonner installation. The guns had an ammunition load of up to 500 round per gun. (Wolfgang Tamme)

[MISSING_PAGE_FAIL:37]

## FuG 240 _Berlin \(N\)-Ia_

FuG 240 _Berlin_ radar was introduced during the last month of the war, with only some twenty-five to thirty sets being issued to service units. Offering contact ranges comparable to FuG 218 _Nguyen_, the FuG 240 weighed just under 400 pounds and featured a technologically advanced nose-mounted dish antenna instead of the usual maze of dipole elements. The dish antenna was protected by a blunt wooden nose cap which provided the cleanest possible configuration of the Ju 88 G-6.

The FuG 218 _Nguyen_ radar entered service during the final months of the war. This Ju 860-6 of \(\tau\)-MJ 6 (coded C+4N), was shown to Switzerland on 30 April 1945, and was later placed on public display. It was equipped with FuG 218 nose and all four-warning antennas. It was heavily regynved with Dark Green uppersurfaces. (Hans-Heil Stapfer)

The forward antennas of the FuG 218 were similar to the earlier FuG 220 SN-2, but was smaller and mounted on a single center line main mast. The small bulb under the nose is a White navigation light. (Manfred Grieht)
**Specifications**

Junkers Ju 88G-6

Wingapan

56 feet 7.5 inches

Length

54 feet (entries with radar type)

Height

15 feet (s)

Maximum Weight

27.337 pounds

Powerplant

Two 1.756 bo (s)

liquid coded engines

Armament

Four 200x cameras in under-baseline

pool. One or Two upward fitting 200x

camories and one 13x near fitting

machine gun.

Performance

Maximum Speed

360 mph

Service ceiling

13.515 feet

Range

13.564 miles

Crew

Three or Four

## Ju 88g-7

The considered to be a major variant, and often confused with the Ju88G-6, the Ju88G-7 was undergoing development when the war ended and did not enter production. According to German documents, the Ju88G-7 was developed from the Ju88G-6, but was equipped with two James J215E-1 engines with MW 50 (water methanol) boost systems driving four-loaded V8-19 middle blade propellers. Provisionally, the signs were to be extended with outer wing panels of the Ju88 series, providing a total span of 726 Te2 inches. Armanant was similar to that of the Ju88G-6, including the rear lifting MG 131 machine gun and two rearward mounted 20mM _Skudge-Music_ sensors.

The proposed radar for the Ju88G-7 was to be the Frido 202 SNS-2 employing the _Grogun_ antenna arrangement, or the Fuo 240 _Borin_ radar. The crew was specified as four men. Wing and fuselace fuel loads were comparable to the Ju88G-6 (874 gallons 2035 lines). Alternate sources are considered that the Ju88G-7 was 140 g/cm\({}^{3}\) and 139.76 miles, a weight of 2892 pounds and a ceiling of 32.340 feet.

Among the known prototypes were then Ju88G-112. V13, V14 and V15. The first two prototypes, which were ordered in November of 1984, were destroyed by Allied bombing in March of 1985. The Ju88V-114 and V115 were reportedly undergoing assembly in Cassini during March and April of 1945, but had not yet received their power plants.

## Ju 88g-10

Intended as an ultra-long-range night-fighter, the Ju88G-10 was basically a Ju88G-6, with an extended fuselage (8 feet 11 3/4 inches) housing additional fuel tanks. The aircraft was powered by 17.509 Daurks Jump 213A liquid cooled in-line engines and ramament was provisionally to have been the same as the Ju88G-6.

Construction of the Ju88G-10 was begun during early 1945 and prototype flight trials ran into the Spring of that year. Only a small number of Ju88G-7 were actually completed. These, however, were not to sensorie units in their intended role. As the star situation continued to deteriorate, most 188G-10 was reassigned to the _Mixed_ flying-bomb program. They were converted as lower bomb component aircraft, using Focke-Wulf Fur 190 fighters as the control aircraft.

Ju 88P

Within a year after Germany's invasion of the Soviet Union, a sense of alarm had spread over the unexpected increase in the number and quality of Russian armored forces. So yes late 1942, any Luhro aircraft capable of mounting anti-task weapony was being tested and prepared for experimental operations within special _parapexingradfin_ (km-fighting squadars). Modifications of 3888 bomers for the anti-taskr role were undertaken in the field, as well as at various _Ersponberpoints for the mounting frame were located in the rear bomb bay. Although the transparent bomber nose was retained, a fighter type armored windshield, applique armor and extra lower cockpit armor was added for low-altitude crew protection. Crew entry was made through a match on the starboard side of the ventral cannon pod.

Primary testing of the Ju 8BP prototype (alternately referred to as the Ju 8SP V-1) was conducted at the Roperstein branch of the _Eryborgwheelin__Recithin_. It was found that the underside pad and the aircraft's increased loaded weight caused a serious reduction in speed and maneuverability. The recoil and muzzle blast when the 75sdcam common was fired reportedly caused damage to the propellers and a number of landing gear failures also occurred. As a partial solution, the KwK 39 common was replaced with the similar PAR 40 (_Hungbuerkerkanzo_ 40), with a revised straight muzzle wake. Even though the Ju 88P prototype located to suffer testing problems, live-free tests against captured Soviet tanks were successful and plans were approved for a limited production run under the designation Ju 88P-1. Development work on the Ju 8SP series continued, leading to several different variants.

### Ju 88p-1

The Ju 8BP-1 differed from the first prototype in having a metal fighter nose and an optional lower rear firing 7.92mm MG 81Z defensive gun position in the ventral cannon pod. The upper canopy maintained the same configuration as the Ju 88A-4 with two rear firing MG 81 machine guns in a double bulged canopy. Additionally, an optional windshield mounted MOT 81J could be used for forward defense. Like the Ju 88A-4, the Ju 88P-1 was powered by two 1,400 hp 201 engines.

During early 1943, Ju 88P-1 joined other anti-tank aircraft assigned to the _Verseismochronalorume_ _Hungbuerkanzo_ (Experimental Command for Tank Fighting) on the Eastern front. Despite the fact that the Ju 88P and the 11J offer the poorest somewhat performance of all types tested, the Ju 88P was pressed into service with the _Puzzer-garo Staff92_ under the _Fahreber der Hunzegegger_ and laterwith_ _Hungbuerkanzo_ _Hungbuerkanzo_, which served as an evaluation unit. The Ju 88P-1 had restricted maneuverability and its main ramament had a slow rate of fire (usually two rounds per pass).

## Ju 88P-2 and Ju 88P-3

Converted from Ju 88A-4 bombers, the Ju 88P-2 featured a wider ventral pod for carrying two 37mm BK 3.7 (_Bord Kamone_ 3.7cm) cannons. These guns offered an increased rate of fire, less recoil and a proven ability to penetrate Russian armor using Wolfram-core anti-tank rounds. A ventral, rear lifting MG 81Z and two upper, rear firing MG 81J machine guns were maintained for defense. High profile armored windshields and applique armor were provided for protection of the crew.

Identical to the Ju 88P-2, the Ju 88P-3 featured additional armor plating to protect the engine and crew against ground fire. While the Ju 88P-2 was alternately considered to be an "anti-bonber" heavy fighter, the P-3 was intended solely for ground-attack and anti-tank duties.

## 5 Ju 88p-4

The last of the Ju 88P series, the Ju 88P-4 centered production during 1944, on a limited basis. It was similar to the Ju 88P-1, but featured a revised cannon pool housing a single 80MB RS common. Defensive machine gain positions remained the same as the Ju 88P-1, although sources also indicated the possibility of a single rear firing MG 131 canopy machine gun, as well as optional ETC bomb tracks for ground-attack missions.

## 6 Final Operations

Unfortunately, little was gained with the Ju 88P, since they all suffered from poor performance. Their average speed of 244 mph left them susceptible to enemy ground fire and fighter interception.

The Ju 88P-2s were briefly used daylight interceptions of American bombers, where their slow speed rendered them next to useless. Later, one Ju 88P were used as experimental radar-equipped night-fighters, with modified ventral spots housing lower caliber weapons. Finally, surviving Ju 88P-3s and Ju 88P-4s were reportedly assigned to _Nachoschacht_ (Night Ground-attack) units during the closing months of the war.

* [15] S.-T. Qi, was a Jul 1982 converted into a personal transport for GEN Field Marshall Enard Mach. The aircraft carries an MG 131 machine quin in the nose position and the entire airport has been heavily respared with LightBlue on the fuselage sides and as a heavy-mottle on the upper surface. (Hams Redeman)
* [16] Mitch's transport conversion retained canopy framing in two tone Green. The fuselage/underling code letters are in Black and fuselage national insights was in a White outline style. (Hams Redeman)

[MISSING_PAGE_EMPTY:47]

The Ju 188E-3 was a limited production torpedo-bomber version of the Ju 188E-1. One PVC rack was carried under each indoor drug standard and torpedo contributions was mounted on the striatumod nose. BBW 8010 engines were standard, while F64200 fabricated anti-shipping search radar was optional. Optional F40 217 rear warning antennas are mounted beneath both wings.

(Left) Crew entry on all Ju 188 was made through a lower fesage hatch, which featured a shelf casing ejection port for the ventral rear firing machine gun (either an MG 131 or MG 121). The light colored streak on the upper nose marks the position of the flare pitad port.

(Bundesarch)
This Jq 188 (WWW 260151) was redesignated the J4 188V-2 and served as the prototype for the second reference verhan. The actual letter served as a test bed for a proposed named tail generator's position. The deepened rear fuselage accommodated the tail turret.

Although it did not enter production, the J4 1888 series was to have been the Zerstor and Nachtiger version of the J4 188. This cabin mock up shows one proposed armament configuration of the fused MQ 151 2000 canons, along with an F40 212 radar and internal arm plate.

Ju 288

Several months before the RLM officially announced the "state of the art" _Bomber B_ program in July of 1939, Junkers designers had commenced worked on an advanced born-per prototype. In fact, the design principals employed by Junkers had heavily influenced the actual criteria set forth in the RLM specifications. Unfortunately, the new bomber, designated the hg 288, was delayed by technical flaws which continually postponed production until the RLM finally cancelled the program during 1943 due to the shifting war situation.

Overall, a total of twenty-two Ju 288 prototypes were constructed, which were aimed at a Ju 288A series (Ju 288V-1 through V-S), a Ju 288B series (Ju 288V-9 through V-14) and a Ju 288C series (Ju 288V-10 through V-105). The original crew cabin was a three seat "bubble" design, which was changed into target prototypes to a four seat configuration. The empenage had twin vertical tails, which remained standard on all the \(k\)288 prototypes. The broad chord shows featured "bench" type whee brakes near the wingting edge, and as development progressed, the wing span was increased from sixty feet (Ju 288V-1) to approximately seventy-four feet (Ju 288V-108).

Due to delays with the proposed Junkers Jump 22A/B (1,690-2,000 hp), Daimler Benz DB 606A/B and DB 610A/B (2,080-2,500 hp) twenty-four cylinder in line liquid cooled engines, the Ju 288V-1 through V-4 and the Ju 288V-7 were flight tested using

Ju 288V-1

Ju 288V-5

Ju 288V-14

Ju 288V-8

Ju 288V-103BMW 801 radial engines. The remaining prototypes, however, were able to use the more powerful inline power plants, driving four blade pipelines. One prototype, the Ju 288V- was brighted itself with a "dotted" propeller spinner.

On all prototypes, the defensive armament consisted of various configurations of remote controlled gun turets in the dorsal, ventral, tall and thin positions. These turets carried either 13mM MG 131 or 20mM MG 151 weapons, in either single or dual mounts. Some prototypes had none mounted fixed toward firing guns, or flexible hand-held weapons in armport spinators.

By the time the last of the Ju 288C prototypes were flown, estimated loaded weight is not a 90,500 pounds. The bomb load was 6,614 pounds carried in the enclosed fuselago bomb and upto,4409 pounds of bombs on optical underbursts. Speed of the Ju 288C was estimated to be 403 mph, with a service ceiling of 34,221 feet.

With the final cancellation of the _Bomber B_ program, the surviving five Ju 288B and Ju 288C prototypes were reportedly fitted with 50mM BK 5 cannons and pressed into combat.

The Ju 388V was to be an all-weather day and night-fighter. The pressurized four-seat cockpit was redesigned with flat armed glass windshield panels and a solid nose for mounting the radar elements. Armament was to consist of four cannons (two 20mM MG 151 and two 30mM MG 1808) housed in an under fuselago conblo, two upward firing MG 151 Schrage _Musk_ cannons, and a remote controlled FHL 131 rail turret with dual 130m MG 131 machine guns (this was to be used on all Ju 388).

Night-fighter equipment was to consist of FuG 220 SN-2 radar with the early "anfer" antennas (the _Morgstrom_ radar with the wooden nose can pass to be installed on late production aircraft). Although several variants of the Ju 388V were planned (Ju 388-1 through J-3), only a few prototypes were actually flown. Production, which had been scheduled for early 1948, had to be cancelled due to the worsening war situation.

The Ju 388J _Z

[MISSING_PAGE_FAIL:52]

## Ju 488

In an effort to produce an advanced four-engined strategic bomber, a proposal was made during 1984 to create a simplified design by combining sub-assemblies of the Ju 188, 288 and 388 and mating them to a new using center section and main fustige. This would produce a select aircraft with a length of 66 feet 87 inches and a wingman of nearly 105 feet. The aircraft was to be powered by four BMW 8017.1 radial engines.

Under the designation 14-88, the first two prototypes (148.88 V401 and V402) had the fustige sections constructed at the Latecore factory at Tolquice in occupied France, while the remaining components were prepared at the Lunkers assembly plants at Dessan and Bernburg. The fuseless were completed by the Summer of 1944, but were heavily damaged by the French resistance just before they were scheduled for shipment to Germany.

Despite this sech, work continued on four additional prototypes (Ju 488 V403 through V406) which were to have featured a deeper fustige with an increased length of just over 66 feet. None of the prototypes for the Ju 488A series were ever completed before the end of the war.

The Ju 488A and an estimated top speed of 338 to 429 mph, a range of 2,110 miles and could carry 11023 pond bomb load. Maximum loaded weight would have been approximately 79,366 pounds.

[MISSING_PAGE_EMPTY:54]