[MISSING_PAGE_EMPTY:2]

## Introduction

_LUFTWAFFE IN ACTION_ is a new concept. Between the covers of this book can be found some of the finest German wormie photographs ever token. There is no text to speak of, since we feel there are enough publications available describing the aircraft in detail, but lacking the photo coverage that the discriminating collector and model builder is seeking.

Each of the photos is unique in the sense that only operational aircraft are shown. These are not manufacturer's publicity photographs that have been seen time after time, but propaganda shots originally meant to be published in German wartime publications. At least 90 percent of the pictures in this book have never been published before and it is our hope that you, the reader, will enjoy them for what they are.

_Mike Dario, Uwe Feist_

_Photoredi:_

Bundesorchiv Kolbenz

Archiv Mike Dario

Helmut Roosenboom

Archiv Uwe Feist

Soudron/Signal Archiv

[MISSING_PAGE_FAIL:4]

The Eastern border of Germany, August, 1939, on the eye of the invasion of Poland; a Snffel of Hs126 reconnaissance glanes like hidden under the true line adjacent to a primary field that will be used for a money.

Another view of the same Snffel of Hs126s. Interesting to note is the removing white horie Sheffield insignia on the aircraft, directly beneath the scheme struts.

As one of the ground crew worms up the engine of this Hs126, the pilot and observer are helped into their parentheses prior to takeoff.

[MISSING_PAGE_EMPTY:6]

takeoff

Right: With the forward energy closed and the engine rearing, the big plane turns into the wind for its relaxed.

Winter operations. As Its126B-1 of 3/Army C-operation Group 21 tracks on the toy runway with its flaps down after returning from a mission over Soviet positions.

Below: The same aircraft, P2+L, in winter comsolonge. The aircraft in the background is a Fock Wall FW189, designed to replace the Hs126, but both types operated side-by-side until the breakdown of the Lufawfle's supply system.

Lett.: A pair of Hs1268-I's wait at a repair door before being returned to the front for more creation. The white white diagonal lines are the frontage side of these and most other Hs1265 were pointed there to aid the observer in lining up his camera with the subjects to be photographed.

[MISSING_PAGE_FAIL:12]

[MISSING_PAGE_EMPTY:13]

Left: K6-GR, on He115B-1, is pulled to share for maintenance on its port floor. Note the large rubber function bladder placed under the tall of the aircraft.

-

Engine maintenance on an He115C. Briefly visible in the photo are the yellow painted winglets on the undersurfaces of the wings.

Below: Battoning up the engines after a long flight. The chin-mounted 15nm 40151 common shows up well in this photo of an He115C.

Lett: A combination of technical knowhow, body english, strong language and brute strength are the tools used to fuse the release pins from the uterus and the floor is free.

A half-dosen mechanics manbould the new floor up to the daily The heavy cost of ice on the ground makes matters only a little easier.

Below: The new floor is placed on the wheeled dolly so that it may be properly positioned under the attachment points on the uterus.

\begin{tabular}{c} \hline \end{tabular}

[MISSING_PAGE_FAIL:21]

A Mag210A-1. Note the absence of the undewewein bomb attachment points; the one main difference between the Me210A-1 and A-2 waitons.

Rigigir: A mechanic worms up the keyboard engine of this Me210. The new canopy batch has been closed in this photo.

The new cockpit of the Me210 showing the sighting mechanism and the remote control firing equipment for the near-firing machine pass.

Right: Maintenance on the remote control equipment. The gun, a 13mm MC131, is seen to advantage with the readerop-shaped firing removed.

[MISSING_PAGE_EMPTY:25]

Figure 1: The same aircraft, showing the stroboard side and the generator plugged into the battery attachment point for networking the batteries.

2HAA was the separation commander's aircraft and was flown on only two occasions - once for these photographs, and the second time, on a comber mission, however before the enemy was connected, the aircraft went into a spin from which the pilot never recovered.

# Focke Wulf FW200

"Condor"

Technical Data

FOCKE WULF FW200 C-3

Producer:

Focke Wulf Flugesweibow GmbH, Bremen

Crew:

7 Men

Type:

Long-range maritime reconnaissance bomber

Dimensions:

Span 107 f. J. m., Length 76 f. 11 in., Height 20 f. 8 in.

Engine:

Faw 9 cylinder BANB Brome 323 R-2 Fafini, air cooled,

1200 h.g.,

Weight:

adapted 50,505 lb.., empty 28,550 lbs.

Performance:

Speed 224 m.p., h, 15,750 lbs.

Range: 2700 miles

Altitude 19,000 ft.

Ammon:

One 7,922 nm. 4635 formed a travel (1000 rounds)

One 13nm MO131 for dorsal (350 rounds)

Two 13nm MO131 for shear beams (300 rounds each)

One 20nm MO131 for blood (500 rounds)

One 7,922 nm. 4635 of system (1000 rounds)

Two 110 lb. boms (50 kg. 550)

Two 550 lbs. boms (250 kg. 550)

Two 1100 lb. boms (500 kg. 550)

The undersurfaces of this FW200 C3/U1 of KG40 are mirrored in the puddles on the Merignoe: hardnessed as it runs up its engines prior to takeoff.

Figure 1942: "Immunism III", the FW200 V3 2640 which was Adolf Hiller's personal transpor aircraft, shown here is standard warming two-tone green spillover-pattern composed finger. The two-sided controlled pitch propellers were standard on FW200 VI through V4 aircraft.

Figure 1: The Linfreefie values delivery of a new FP200 C3/U1. Here, the ground crew path the aircraft moved its place on the taxi strip.

_Right: A "Cender" circles the runway to gain altitude._

The FW200 C3 peaks across the field for another sorting during the Damponsk uplift.

_Below: This C3 is a real veteran! Her redder shows that the such two filled ships while a member of KG40 in France; the new bears the marking of Instrument Flight School 36, but is being used as a corps wrapper during the emergency uplift._

[MISSING_PAGE_FAIL:36]

[MISSING_PAGE_EMPTY:37]

A He580-2, PYNI is hosted up to be placed in the water. Note the backhing dollies directly below the floors in this photo.

Left: Here's a switch - the two boost is being searched by a member of the Luff-waffle while members of the Kreismarines check the fibers and rigging of the floorplane after a flight.

Heinkel He60D Seagplane

Tess of the first He60d prototype revealed excellent flight characteristics, but proved the plane to be undersovered.

Paweyed to 750 h, p.b. sharp II cylinder engine, the He60D did not show any big improvements, therefore it was decided to retain the original power plant.

Arado Fluggevawte and Weser Fluggevob showed in the production of the flioplong, building 100 each.

Six Heinkel He60D's purchased by the Spanish Nationalist Forces, were sent to Spain 1936 with the Legion Condor.

With his limited defensive comment and low performance, the He60 was withdrawn from first dive in the early months of the war.

Continuing to operate in a secondary role up to late 1943, the flioplong was finally removed from the Luftroffie's inventory.

Technical Data HEINKLE He60C Float Seagplane

Producer: Arado Fluggevawte, Weser Fluggevob

Genev: 2 men: pilot, younger-observer

Type: 3her range reconnaissance plane

Dimensions: 5942 H, 4 in., Length 37 hr, 8 in.,

Height 16 hr

Engine:  One II cylinder Baw V1 Zu liquid cooled,

460 h, p.b.

Weight: 1.00ed 7840 lbs., empty S310 lbs.

Performance:  Speed: 140 m.b.

Range: 300 m/lbs

Altitude: 16,40 hr

Ammonent:  One 7.92m, 4015 l flexible mounted rear

firing (820 rounds)

A He60D SD'WJ roors across the calm water before lifting off on patrol.

K0+PF, a He60D of Coastal Group 406 flies low over a convey bound for Norway during the Norwegian Campaign of 1940.

Arado Ar96B Trainer

An Ar96B of Fisher School 2. Note the trough for the single forward-firing machine gun on the engine cowling.

In late 1936, the prototype of the Aerdo's newly designed trainer, the Ary6V1 mode its first test flights. Production of the Ar96 began in 1939, making the low winged membrane the standard tether of the Leltwtwefle.

The excellent handling choreacteristics and robust construction mode the Arodo Ar96 0 very safe plane for students to fly, keeping accidents down to minimum.

Built throughout the war in great numbers, a tool of approximately 3500 Ary65's left the production lines of Aedo and Leltwic in Czechoslovakia. The Ar96B was powered by an Arggus 12 cylinder \(\mathrm{A}\)s 410 A engine which also powered the early Ranchelt \(\mathrm{A}\)s129 and the Fock Wulf F89 (see Soderboom/Singl Aircraft Inc. 1).

Leltw continued producing the Ar96B for the new Czechoslovakia Air Force until late 1948 when the lst C. 2 B-1 (Ar96B) left the production line.

[MISSING_PAGE_EMPTY:43]

Cotha Go242 Cilider

With a capacity to accommodate up to 21 fully equipped soldiers, as well as 2 crew members, the Go242 Cilider played a vital role in supplying encircled troops on the Eastern Front, bringing in reinforcements and evacuting consoliutes.

Decisions to develop a transport glider were prompted by the successful employment of the P52320 filter in the West.

The glider was of plywood-fabric and welded steel tube construction with a steel empty weight of 7000 lbs.

Flight resting began in early 1941 and the first dozen gliders were delivered to the Luftawfle in August of the some year.

A total of approximately 1400 Go242 Lastensegler (gliders) were built when production stopped in the middle of 1944, with an additional 135 aircraft being converted into powered Go244 ergo-trope transports.

Cotha Go242 Cilider

Producer

Gothner Weggenofabrik A.G.

Crewi

2 menil pilod and c-pilider

Typei

Assult and transport-glider

Dimensions:

Span 80 ft. 4 in., Length 51 ft. 10 in., Height 13 ft. 11 in., Height 16,100 lbs. maximum overload

Empty 7000 lbs.

Performonce:

Speed 180 m.p.h., pilding

Towing speed 140 m.p.h. maximum

Four 7.92mn MG15

A Gothe with a unique sharkonuth design being loaded in Sicily before a flight to Tuniie. The Luftawfle office in the foreground is wearing his summer khaki uniform, white heat cover, and footwear that are most appropriate, but do not seem to be Tehranch or Luftawfle issue.

[MISSING_PAGE_EMPTY:46]

[MISSING_PAGE_EMPTY:48]